# Generated by Django 4.2.4 on 2023-09-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "AppRentCar",
            "0015_alter_car_cars_type_alter_car_drive_alter_car_engine_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="rent",
            name="canceled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rent",
            name="status",
            field=models.CharField(
                choices=[
                    ("Oczekuje", "Oczekuje"),
                    ("W trakcie", "W trakcie"),
                    ("Zakończono", "Zakończono"),
                    ("Anulowano", "Anulowano"),
                ],
                default="Oczekuje",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="cars_type",
            field=models.CharField(
                choices=[
                    ("Hatchback", "Hatchback"),
                    ("Shooting brake", "Shooting brake"),
                    ("Van", "Van"),
                    ("Kombi", "Kombi"),
                    ("Coupe", "Coupe"),
                    ("Sedan", "Sedan"),
                    ("Suv", "Suv"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="drive",
            field=models.CharField(
                choices=[("4x4", "4x4"), ("Tylni", "Tylni"), ("Przedni", "Przedni")],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="engine",
            field=models.CharField(
                choices=[
                    ("Hybryda", "Hybryda"),
                    ("Diesel", "Diesel"),
                    ("Benzyna", "Benzyna"),
                    ("Elektryczny", "Elektryczny"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="no_gears",
            field=models.CharField(
                choices=[("6", "6"), ("7", "7"), ("8", "8"), ("5", "5")], max_length=8
            ),
        ),
    ]
