# Generated by Django 4.2.4 on 2023-09-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppRentCar", "0016_rent_canceled_rent_status_alter_car_cars_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rent",
            name="canceled",
        ),
        migrations.RemoveField(
            model_name="rent",
            name="status",
        ),
        migrations.AlterField(
            model_name="car",
            name="cars_type",
            field=models.CharField(
                choices=[
                    ("Van", "Van"),
                    ("Suv", "Suv"),
                    ("Kombi", "Kombi"),
                    ("Hatchback", "Hatchback"),
                    ("Sedan", "Sedan"),
                    ("Shooting brake", "Shooting brake"),
                    ("Coupe", "Coupe"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="drive",
            field=models.CharField(
                choices=[("Przedni", "Przedni"), ("4x4", "4x4"), ("Tylni", "Tylni")],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="engine",
            field=models.CharField(
                choices=[
                    ("Diesel", "Diesel"),
                    ("Elektryczny", "Elektryczny"),
                    ("Benzyna", "Benzyna"),
                    ("Hybryda", "Hybryda"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="transmission",
            field=models.CharField(
                choices=[("Automatyczna", "Automatyczna"), ("Manuala", "Manualna")],
                max_length=32,
            ),
        ),
    ]
