# Generated by Django 4.2.4 on 2023-09-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppRentCar", "0017_remove_rent_canceled_remove_rent_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="capacity",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="cars_type",
            field=models.CharField(
                choices=[
                    ("Shooting brake", "Shooting brake"),
                    ("Sedan", "Sedan"),
                    ("Van", "Van"),
                    ("Suv", "Suv"),
                    ("Kombi", "Kombi"),
                    ("Cabrio", "Cabrio"),
                    ("Coupe", "Coupe"),
                    ("Hatchback", "Hatchback"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="drive",
            field=models.CharField(
                choices=[("4x4", "4x4"), ("Tylni", "Tylni"), ("Przedni", "Przedni")],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="engine",
            field=models.CharField(
                choices=[
                    ("Diesel", "Diesel"),
                    ("Benzyna", "Benzyna"),
                    ("Elektryczny", "Elektryczny"),
                    ("Hybryda", "Hybryda"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="no_gears",
            field=models.CharField(
                choices=[("7", "7"), ("5", "5"), ("8", "8"), ("6", "6")], max_length=8
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="transmission",
            field=models.CharField(
                choices=[("Manuala", "Manualna"), ("Automatyczna", "Automatyczna")],
                max_length=32,
            ),
        ),
    ]
