# Generated by Django 4.2.4 on 2023-09-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppRentCar", "0018_alter_car_capacity_alter_car_cars_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="cars_type",
            field=models.CharField(
                choices=[
                    ("Suv", "Suv"),
                    ("Cabrio", "Cabrio"),
                    ("Hatchback", "Hatchback"),
                    ("Van", "Van"),
                    ("Sedan", "Sedan"),
                    ("Shooting brake", "Shooting brake"),
                    ("Coupe", "Coupe"),
                    ("Kombi", "Kombi"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="drive",
            field=models.CharField(
                choices=[("Tylni", "Tylni"), ("4x4", "4x4"), ("Przedni", "Przedni")],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="engine",
            field=models.CharField(
                choices=[
                    ("Elektryczny", "Elektryczny"),
                    ("Diesel", "Diesel"),
                    ("Benzyna", "Benzyna"),
                    ("Hybryda", "Hybryda"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="no_gears",
            field=models.CharField(
                choices=[("7", "7"), ("5", "5"), ("6", "6"), ("8", "8")], max_length=8
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="transmission",
            field=models.CharField(
                choices=[("Automatyczna", "Automatyczna"), ("Manuala", "Manualna")],
                max_length=32,
            ),
        ),
    ]
